compile_transpose:
	javac Transpose.java

compile_matrix_star:
	javac MatrixStar.java

compile_bin_repr:
	javac BinRepr.java

compile_between_zero_one:
	javac BetweenZeroOne.java

compile_three_args_equal:
	javac ThreeArgsEqual.java

run_hello_world:
	javac HelloWorld.java
	java HelloWorld

.PHONY: clean
clean:
	rm -f HelloWorld.class
	rm -f ThreeArgsEqual.class
	rm -f BetweenZeroOne.class
	rm -f BinRepr.class
	rm -f MatrixStar.class
	rm -f Transpose.class
